### ISSUE TITLE
armv6 for Raspberry Pi 0

### ISSUE THREAD

**Issue by johnnychicago** [jippi/docker-ser2net#2]
Hello --

Just wanted to play with this on a Pi 0 and couldn't get a working image:

`WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested`

Would it be feasible to build a container that works on the Pi 0? Currently building my own, but that's way less elegant than just pulling it :)

The Pi 0 is probably a nice platform for this kind of tool, isn't it?

**Comment by jippi** [comment]
I don't have a Pi Zero to test with, but you can try adding it here https://github.com/jippi/docker-ser2net/blob/master/lib/bootstrap.sh#L71 and see if it just works - if it does, then yes, we should 100% do it :)

**Comment by johnnychicago** [comment]
My apologies, I left for vacation shortly after playing with this and totally forgot to come back.

I managed to build the container (after adjusting some minor thing, would need to go back and look), but did not get things to work in a stable way. To be fair, that was mentioned right at the application's howto (https://www.zigbee2mqtt.io/advanced/remote-adapter/connect_to_a_remote_adapter.html)

Not sure if this is a general issue with wifi connected devices and ser2net - if so, adding the Pi Zero might be less useful, since it's wifi only.

**Comment by Caroga** [comment]
Hi there! I'd love for this to be available for RPI 0 platform. I have a Zero W running ser2net at the moment and am looking to replace the current image with the one from this repository. 

Is there anything I could provide in order to help?

**Comment by jippi** [comment]
Hey! So according to [Ubuntu RaspberryPi docs](https://wiki.ubuntu.com/ARM/RaspberryPi)

> The original (ARMv6) based Raspberry Pis, including the A, B, B+, 0 and 0W, are not supported under Ubuntu.

I honestly don't have the time to figure out an Alpine or alternative distribution for armv6, so unless someone can contribute and test it doesn't break the existing systems, I'm going to close this as a `can't fix` for now
